// packages/tui-adapter-solid/src/components/screen/loading_message.tsx
import { createSignal, createEffect, onCleanup } from 'solid-js'

import { LogMessage } from '../log/index.ts'

import type { LoadingMessageData, LogMessageVariant } from '@navios/commander-tui'

const SPINNER_FRAMES = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']

export interface LoadingMessageProps {
  message: LoadingMessageData
}

export function LoadingMessage(props: LoadingMessageProps) {
  const [frameIndex, setFrameIndex] = createSignal(0)

  createEffect(() => {
    if (props.message.status === 'loading') {
      const interval = setInterval(() => {
        setFrameIndex((prev) => (prev + 1) % SPINNER_FRAMES.length)
      }, 80)

      onCleanup(() => clearInterval(interval))
    }
  })

  // Map loading status to log level and variant for display
  const level = () => (props.message.status === 'fail' ? 'error' : 'log')
  const variant = (): LogMessageVariant | undefined =>
    props.message.status === 'success' ? 'success' : undefined

  const displayContent = () => props.message.resolvedContent ?? props.message.content
  const spinner = () => (props.message.status === 'loading' ? SPINNER_FRAMES[frameIndex()] + ' ' : '')

  return (
    <LogMessage level={level()} variant={variant()} timestamp={props.message.timestamp}>
      {spinner() + displayContent()}
    </LogMessage>
  )
}

// packages/tui-adapter-react/src/components/screen/loading_message.tsx
import { useState, useEffect, useRef } from 'react'

import type { LoadingMessageData, LogMessageVariant } from '@navios/commander-tui'

import { LogMessage } from '../log/index.ts'

const SPINNER_FRAMES = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']

export interface LoadingMessageProps {
  message: LoadingMessageData
}

export function LoadingMessage({ message }: LoadingMessageProps) {
  const [frameIndex, setFrameIndex] = useState(0)
  const intervalRef = useRef<ReturnType<typeof setInterval> | null>(null)

  useEffect(() => {
    if (message.status === 'loading') {
      intervalRef.current = setInterval(() => {
        setFrameIndex((prev) => (prev + 1) % SPINNER_FRAMES.length)
      }, 80)
    }

    return () => {
      if (intervalRef.current) {
        clearInterval(intervalRef.current)
      }
    }
  }, [message.status])

  // Map loading status to log level and variant for display
  const level = message.status === 'fail' ? 'error' : 'log'
  const variant: LogMessageVariant | undefined =
    message.status === 'success' ? 'success' : undefined

  const displayContent = message.resolvedContent ?? message.content
  const spinner = message.status === 'loading' ? SPINNER_FRAMES[frameIndex] + ' ' : ''

  return (
    <LogMessage level={level} variant={variant} timestamp={message.timestamp}>
      {spinner + displayContent}
    </LogMessage>
  )
}
