// packages/commander-tui/src/adapters/solid/components/screen_manager_bridge.tsx
import { useKeyboard } from '@opentui/solid'
import { createSignal, createEffect, createMemo, onCleanup, Show } from 'solid-js'

import { LoggerProvider } from '../context/index.ts'
import { FilterEngine } from '../../../filter/index.ts'
import { KeyboardManager, createDefaultBindings, handlePrintableInput } from '../../../keyboard/index.ts'
import {
  ALL_LOG_LEVELS,
  createDefaultFilterState,
  hasActiveFilter,
  type FilterState,
  type KeyboardContext,
  type Theme,
} from '../../../types/index.ts'

import type { ScreenManagerInstance } from '../../../services/index.ts'

import { FilterBar } from './filter/filter_bar.tsx'
import { HelpOverlay } from './help/help_overlay.tsx'
import { ScreenBridge } from './screen/screen_bridge.tsx'
import { Sidebar } from './sidebar/sidebar.tsx'

export interface ScreenManagerBridgeProps {
  manager: ScreenManagerInstance
  theme?: Theme
}

export function ScreenManagerBridge(props: ScreenManagerBridgeProps) {
  const [version, setVersion] = createSignal(0)
  const [showHelp, setShowHelp] = createSignal(false)
  const [filter, setFilter] = createSignal<FilterState>(createDefaultFilterState())

  // Subscribe to manager changes
  createEffect(() => {
    const unsub = props.manager.onChange(() => setVersion((v) => v + 1))
    onCleanup(() => unsub())
  })

  // Helper functions for keyboard bindings
  const getActiveScreen = () => props.manager.getActiveScreen()

  const toggleHelp = () => {
    setShowHelp((prev) => !prev)
  }

  const toggleFilter = () => {
    setFilter((prev) => ({
      ...prev,
      isVisible: !prev.isVisible,
      focusedField: 'search',
    }))
  }

  const closeFilter = () => {
    setFilter((prev) => ({ ...prev, isVisible: false }))
  }

  const filterAppendChar = (char: string) => {
    setFilter((prev) => ({
      ...prev,
      searchQuery: prev.searchQuery + char,
    }))
  }

  const filterDeleteChar = () => {
    setFilter((prev) => ({
      ...prev,
      searchQuery: prev.searchQuery.slice(0, -1),
    }))
  }

  const filterToggleLevel = (index: number) => {
    setFilter((prev) => {
      const level = ALL_LOG_LEVELS[index]
      if (!level) return prev

      const newLevels = new Set(prev.enabledLevels)
      if (newLevels.has(level)) {
        newLevels.delete(level)
      } else {
        newLevels.add(level)
      }

      return { ...prev, enabledLevels: newLevels }
    })
  }

  const filterCycleField = () => {
    setFilter((prev) => ({
      ...prev,
      focusedField: prev.focusedField === 'search' ? 'levels' : 'search',
    }))
  }

  // Create keyboard manager with bindings
  const keyboardManager = createMemo(() => {
    const km = new KeyboardManager()
    const bindings = createDefaultBindings({
      manager: props.manager,
      getActiveScreen,
      toggleHelp,
      toggleFilter,
      closeFilter,
      filterAppendChar,
      filterDeleteChar,
      filterToggleLevel,
      filterCycleField,
    })
    km.addBindings(bindings)
    return km
  })

  // Keyboard handler
  const handleKeyboard = (key: { name: string; ctrl?: boolean; meta?: boolean; sequence?: string }) => {
    const screens = props.manager.getScreens()
    const activeScreen = props.manager.getActiveScreen()

    const context: KeyboardContext = {
      hasSidebar: screens.length > 1,
      focusArea: props.manager.focusArea,
      hasPrompt: activeScreen?.hasActivePrompt() ?? false,
      inInputMode: activeScreen?.isPromptInInputMode() ?? false,
      isFilterActive: filter().isVisible,
      isHelpVisible: showHelp(),
    }

    // Try keyboard manager first
    if (keyboardManager().handleKey(key, context)) {
      return
    }

    // Handle printable characters (for input mode and filter)
    handlePrintableInput(key, context, {
      manager: props.manager,
      getActiveScreen,
      toggleHelp,
      toggleFilter,
      closeFilter,
      filterAppendChar,
      filterDeleteChar,
      filterToggleLevel,
      filterCycleField,
    })
  }

  // Handle keyboard input
  useKeyboard(handleKeyboard)

  // Derived state
  const screens = () => {
    version() // Track for reactivity
    return props.manager.getScreens()
  }

  const activeScreen = () => {
    version() // Track for reactivity
    return props.manager.getActiveScreen()
  }

  const activeScreenId = () => activeScreen()?.getId() ?? screens()[0]?.getId() ?? ''
  const bindOptions = () => props.manager.getBindOptions()
  const hasSidebar = () => screens().length > 1

  // Subscribe to active screen version for level counts
  const [activeScreenVersion, setActiveScreenVersion] = createSignal(0)

  createEffect(() => {
    const screen = activeScreen()
    if (screen) {
      const unsub = screen.onChange(() => setActiveScreenVersion((v) => v + 1))
      onCleanup(() => unsub())
    }
  })

  // Get level counts for filter bar
  const levelCounts = createMemo(() => {
    activeScreenVersion() // Track for reactivity
    const screen = activeScreen()
    if (!screen) {
      return {
        verbose: 0,
        debug: 0,
        log: 0,
        warn: 0,
        error: 0,
        fatal: 0,
      }
    }
    return FilterEngine.countByLevel(screen.getMessages())
  })

  // Filter messages for the active screen
  const filteredMessages = createMemo(() => {
    activeScreenVersion() // Track for reactivity
    const screen = activeScreen()
    if (!screen) return []
    return FilterEngine.filterMessages(screen.getMessages(), filter())
  })

  const isFiltering = createMemo(() => hasActiveFilter(filter()))

  return (
    <LoggerProvider theme={props.theme}>
      <box flexDirection="row" flexGrow={1}>
        {/* Sidebar */}
        <Show when={hasSidebar()}>
          <Sidebar
            screens={screens()}
            selectedIndex={props.manager.selectedIndex}
            activeScreenId={activeScreenId()}
            focused={props.manager.focusArea === 'sidebar'}
            width={bindOptions().sidebarWidth ?? 25}
            title={bindOptions().sidebarTitle ?? 'Screens'}
          />
        </Show>

        {/* Main content area */}
        <box flexDirection="column" flexGrow={1}>
          {/* Filter bar */}
          <Show when={filter().isVisible}>
            <FilterBar filter={filter()} levelCounts={levelCounts()} />
          </Show>

          {/* Screen content */}
          <Show when={activeScreen()}>
            <ScreenBridge
              screen={activeScreen()!}
              focused={props.manager.focusArea === 'content'}
              filteredMessages={filteredMessages()}
              isFiltering={isFiltering()}
              totalMessages={activeScreen()!.getMessages().length}
            />
          </Show>
        </box>

        {/* Help overlay */}
        <Show when={showHelp()}>
          <HelpOverlay bindings={keyboardManager().getBindingsForHelp()} />
        </Show>
      </box>
    </LoggerProvider>
  )
}

// packages/commander-tui/src/adapters/ink/components/screen_manager_bridge.tsx
import { Box, useInput } from 'ink'
import { useState, useCallback, useMemo, useSyncExternalStore } from 'react'

import { LoggerProvider } from '../context/index.ts'
import { useManagerSubscription, useFilterState, useKeyboardManager } from '../../react-shared/index.ts'
import { FilterEngine } from '../../../filter/index.ts'
import {
  hasActiveFilter,
  type Theme,
} from '../../../types/index.ts'

import type { ScreenManagerInstance } from '../../../services/index.ts'

import { FilterBar } from './filter/filter_bar.tsx'
import { HelpOverlay } from './help/help_overlay.tsx'
import { ScreenBridge } from './screen/screen_bridge.tsx'
import { Sidebar } from './sidebar/sidebar.tsx'

export interface ScreenManagerBridgeProps {
  manager: ScreenManagerInstance
  theme?: Theme
}

/**
 * Maps Ink's key format to the normalized format expected by KeyboardManager.
 */
function mapInkKeyToName(
  key: {
    upArrow?: boolean
    downArrow?: boolean
    leftArrow?: boolean
    rightArrow?: boolean
    return?: boolean
    escape?: boolean
    backspace?: boolean
    delete?: boolean
    tab?: boolean
    ctrl?: boolean
    meta?: boolean
    shift?: boolean
  },
  input: string,
): string {
  if (key.upArrow) return 'up'
  if (key.downArrow) return 'down'
  if (key.leftArrow) return 'left'
  if (key.rightArrow) return 'right'
  if (key.return) return 'return'
  if (key.escape) return 'escape'
  if (key.backspace) return 'backspace'
  if (key.delete) return 'delete'
  if (key.tab) return 'tab'

  // For regular characters
  return input
}

export function ScreenManagerBridge({ manager, theme }: ScreenManagerBridgeProps) {
  // Subscribe to manager changes
  useManagerSubscription(manager)

  const [showHelp, setShowHelp] = useState(false)
  const [filter, filterActions] = useFilterState()

  const toggleHelp = useCallback(() => {
    setShowHelp((prev) => !prev)
  }, [])

  // Create keyboard manager with bindings
  const { keyboardManager, handleKeyboard } = useKeyboardManager(
    {
      manager,
      toggleHelp,
      filterActions,
    },
    filter.isVisible,
    showHelp,
  )

  // Handle keyboard input using Ink's useInput
  useInput((input, key) => {
    const normalizedKey = {
      name: mapInkKeyToName(key, input),
      ctrl: key.ctrl,
      meta: key.meta,
      sequence: input,
    }

    handleKeyboard(normalizedKey)
  })

  const screens = manager.getScreens()
  const activeScreen = manager.getActiveScreen()
  const activeScreenId = activeScreen?.getId() ?? screens[0]?.getId() ?? ''
  const bindOptions = manager.getBindOptions()
  const hasSidebar = screens.length > 1

  const activeScreenVersion = useSyncExternalStore(
    (updater) => activeScreen?.onChange(updater) ?? (() => {}),
    () => activeScreen?.getVersion() ?? -1,
  )

  // Get level counts for filter bar
  const levelCounts = useMemo(() => {
    if (!activeScreen) {
      return {
        verbose: 0,
        debug: 0,
        log: 0,
        warn: 0,
        error: 0,
        fatal: 0,
      }
    }
    return FilterEngine.countByLevel(activeScreen.getMessages())
  }, [activeScreenVersion, activeScreen])

  // Filter messages for the active screen
  const filteredMessages = useMemo(() => {
    if (!activeScreen) return []
    return FilterEngine.filterMessages(activeScreen.getMessages(), filter)
  }, [activeScreenVersion, activeScreen, filter])

  const isFiltering = useMemo(() => hasActiveFilter(filter), [filter])

  return (
    <LoggerProvider theme={theme}>
      <Box flexDirection="row" flexGrow={1}>
        {/* Sidebar */}
        {hasSidebar && (
          <Sidebar
            screens={screens}
            selectedIndex={manager.selectedIndex}
            activeScreenId={activeScreenId}
            focused={manager.focusArea === 'sidebar'}
            width={bindOptions.sidebarWidth ?? 25}
            title={bindOptions.sidebarTitle ?? 'Screens'}
          />
        )}

        {/* Main content area */}
        <Box flexDirection="column" flexGrow={1}>
          {/* Filter bar */}
          {filter.isVisible && <FilterBar filter={filter} levelCounts={levelCounts} />}

          {/* Screen content */}
          {activeScreen && (
            <ScreenBridge
              key={activeScreen.getId()}
              screen={activeScreen}
              focused={manager.focusArea === 'content'}
              filteredMessages={filteredMessages}
              isFiltering={isFiltering}
              totalMessages={activeScreen.getMessages().length}
            />
          )}
        </Box>

        {/* Help overlay */}
        {showHelp && <HelpOverlay bindings={keyboardManager.getBindingsForHelp()} />}
      </Box>
    </LoggerProvider>
  )
}
