// packages/tui-adapter-solid/src/components/prompt/prompt_renderer.tsx
import { TextAttributes } from '@opentui/core'
import { Show, For, Switch, Match } from 'solid-js'

import type {
  PromptData,
  ChoicePromptData,
  ConfirmPromptData,
  InputPromptData,
  MultiChoicePromptData,
  PromptTheme,
} from '@navios/commander-tui'

import { useTheme } from '../../hooks/index.ts'

export interface PromptRendererProps {
  prompt: PromptData
}

export function PromptRenderer(props: PromptRendererProps) {
  const theme = useTheme()
  // Calculate timeout remaining if applicable
  const timeoutRemaining = () => getTimeoutRemaining(props.prompt)

  return (
    <Switch fallback={null}>
      <Match when={props.prompt.type === 'choice'}>
        <ChoicePromptRenderer
          prompt={props.prompt as ChoicePromptData}
          timeoutRemaining={timeoutRemaining()}
          colors={theme.prompt}
        />
      </Match>
      <Match when={props.prompt.type === 'confirm'}>
        <ConfirmPromptRenderer
          prompt={props.prompt as ConfirmPromptData}
          timeoutRemaining={timeoutRemaining()}
          colors={theme.prompt}
        />
      </Match>
      <Match when={props.prompt.type === 'input'}>
        <InputPromptRenderer
          prompt={props.prompt as InputPromptData}
          timeoutRemaining={timeoutRemaining()}
          colors={theme.prompt}
        />
      </Match>
      <Match when={props.prompt.type === 'multiChoice'}>
        <MultiChoicePromptRenderer
          prompt={props.prompt as MultiChoicePromptData}
          timeoutRemaining={timeoutRemaining()}
          colors={theme.prompt}
        />
      </Match>
    </Switch>
  )
}

function getTimeoutRemaining(prompt: PromptData): number | null {
  if (!prompt.timeout || !prompt.timeoutStarted) return null
  const elapsed = Date.now() - prompt.timeoutStarted
  const remaining = Math.max(0, prompt.timeout - elapsed)
  return Math.ceil(remaining / 1000)
}

function TimeoutIndicator(props: { seconds: number | null; colors: PromptTheme }) {
  return (
    <Show when={props.seconds !== null}>
      <text fg={props.colors.optionTextDim} attributes={TextAttributes.DIM}>
        {' '}
        (auto-select in {props.seconds}s)
      </text>
    </Show>
  )
}

interface ChoicePromptRendererProps {
  prompt: ChoicePromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function ChoicePromptRenderer(props: ChoicePromptRendererProps) {
  return (
    <box
      flexDirection="column"
      borderColor={props.colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={props.colors.question} attributes={TextAttributes.BOLD}>
          ? {props.prompt.question}
        </text>
        <TimeoutIndicator seconds={props.timeoutRemaining} colors={props.colors} />
      </box>

      {/* Choices */}
      <box flexDirection="column">
        <For each={props.prompt.choices}>
          {(choice, index) => {
            const isSelected = () => index() === props.prompt.selectedIndex
            const showInput = () => isSelected() && choice.input && props.prompt.inputMode

            return (
              <box flexDirection="row">
                {/* Selection indicator */}
                <text fg={isSelected() ? props.colors.optionSelected : 'transparent'}>{'>'} </text>

                {/* Choice label */}
                <text
                  fg={isSelected() ? props.colors.optionText : props.colors.optionTextDim}
                  attributes={isSelected() ? TextAttributes.BOLD : undefined}
                >
                  {choice.label}
                </text>

                {/* Input field (if applicable) */}
                <Show when={showInput()}>
                  <box flexDirection="row" marginLeft={1}>
                    <text fg={props.colors.inputText}>: </text>
                    <text fg={props.colors.inputText}>{props.prompt.inputValue}</text>
                    <text fg={props.colors.inputCursor} attributes={TextAttributes.BLINK}>
                      _
                    </text>
                  </box>
                </Show>

                {/* Show hint for input option when selected but not in input mode */}
                <Show when={isSelected() && choice.input && !props.prompt.inputMode}>
                  <text fg={props.colors.optionTextDim}> (press Enter to type)</text>
                </Show>
              </box>
            )
          }}
        </For>
      </box>

      {/* Instructions */}
      <Show
        when={props.prompt.inputMode}
        fallback={
          <text fg={props.colors.optionTextDim} attributes={TextAttributes.DIM}>
            ↑/↓ to navigate, Enter to select
          </text>
        }
      >
        <text fg={props.colors.optionTextDim} attributes={TextAttributes.DIM}>
          Type your answer, Enter to submit, Esc to cancel
        </text>
      </Show>
    </box>
  )
}

interface ConfirmPromptRendererProps {
  prompt: ConfirmPromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function ConfirmPromptRenderer(props: ConfirmPromptRendererProps) {
  const confirmSelected = () => props.prompt.selectedValue === true
  const cancelSelected = () => props.prompt.selectedValue === false

  return (
    <box
      flexDirection="column"
      borderColor={props.colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={props.colors.question} attributes={TextAttributes.BOLD}>
          ? {props.prompt.question}
        </text>
        <TimeoutIndicator seconds={props.timeoutRemaining} colors={props.colors} />
      </box>

      {/* Buttons */}
      <box flexDirection="row" gap={2}>
        {/* Confirm button */}
        <box
          backgroundColor={confirmSelected() ? props.colors.buttonSelectedBackground : undefined}
          paddingLeft={1}
          paddingRight={1}
        >
          <text
            fg={confirmSelected() ? props.colors.confirmButton : props.colors.optionTextDim}
            attributes={confirmSelected() ? TextAttributes.BOLD : undefined}
          >
            {confirmSelected() ? '>' : ' '} {props.prompt.confirmText}
          </text>
        </box>

        {/* Cancel button */}
        <box
          backgroundColor={cancelSelected() ? props.colors.buttonSelectedBackground : undefined}
          paddingLeft={1}
          paddingRight={1}
        >
          <text
            fg={cancelSelected() ? props.colors.cancelButton : props.colors.optionTextDim}
            attributes={cancelSelected() ? TextAttributes.BOLD : undefined}
          >
            {cancelSelected() ? '>' : ' '} {props.prompt.cancelText}
          </text>
        </box>
      </box>

      {/* Instructions */}
      <text fg={props.colors.optionTextDim} attributes={TextAttributes.DIM}>
        ←/→ to select, Enter to confirm
      </text>
    </box>
  )
}

interface InputPromptRendererProps {
  prompt: InputPromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function InputPromptRenderer(props: InputPromptRendererProps) {
  const hasValue = () => props.prompt.value.length > 0

  return (
    <box
      flexDirection="column"
      borderColor={props.colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={props.colors.question} attributes={TextAttributes.BOLD}>
          ? {props.prompt.question}
        </text>
        <TimeoutIndicator seconds={props.timeoutRemaining} colors={props.colors} />
      </box>

      {/* Input field */}
      <box
        flexDirection="row"
        borderColor={props.colors.inputBorder}
        border={['left']}
        paddingLeft={1}
      >
        <text fg={hasValue() ? props.colors.inputText : props.colors.inputPlaceholder}>
          {hasValue() ? props.prompt.value : props.prompt.placeholder}
        </text>
        <text fg={props.colors.inputCursor} attributes={TextAttributes.BLINK}>
          _
        </text>
      </box>

      {/* Instructions */}
      <text fg={props.colors.optionTextDim} attributes={TextAttributes.DIM}>
        Type your answer, Enter to submit
      </text>
    </box>
  )
}

interface MultiChoicePromptRendererProps {
  prompt: MultiChoicePromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function MultiChoicePromptRenderer(props: MultiChoicePromptRendererProps) {
  const selectedCount = () => props.prompt.selectedIndices.size
  const canSubmit = () => selectedCount() >= props.prompt.minSelect

  return (
    <box
      flexDirection="column"
      borderColor={props.colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={props.colors.question} attributes={TextAttributes.BOLD}>
          ? {props.prompt.question}
        </text>
        <text fg={props.colors.optionTextDim}>
          {' '}
          ({selectedCount()}/{props.prompt.maxSelect} selected)
        </text>
        <TimeoutIndicator seconds={props.timeoutRemaining} colors={props.colors} />
      </box>

      {/* Choices */}
      <box flexDirection="column">
        <For each={props.prompt.choices}>
          {(choice, index) => {
            const isFocused = () => index() === props.prompt.focusedIndex
            const isChecked = () => props.prompt.selectedIndices.has(index())

            return (
              <box flexDirection="row">
                {/* Focus indicator */}
                <text fg={isFocused() ? props.colors.optionSelected : 'transparent'}>{'>'} </text>

                {/* Checkbox */}
                <text fg={isChecked() ? props.colors.optionSelected : props.colors.optionTextDim}>
                  {isChecked() ? '[✓]' : '[ ]'}{' '}
                </text>

                {/* Choice label */}
                <text
                  fg={isFocused() ? props.colors.optionText : props.colors.optionTextDim}
                  attributes={isFocused() ? TextAttributes.BOLD : undefined}
                >
                  {choice.label}
                </text>
              </box>
            )
          }}
        </For>
      </box>

      {/* Instructions */}
      <box flexDirection="column">
        <text fg={props.colors.optionTextDim} attributes={TextAttributes.DIM}>
          ↑/↓ to navigate, Space to toggle
        </text>
        <Show
          when={canSubmit()}
          fallback={
            <text fg={props.colors.cancelButton} attributes={TextAttributes.DIM}>
              Select at least {props.prompt.minSelect} option
              {props.prompt.minSelect > 1 ? 's' : ''}
            </text>
          }
        >
          <text fg={props.colors.optionTextDim} attributes={TextAttributes.DIM}>
            Enter to confirm
          </text>
        </Show>
      </box>
    </box>
  )
}

// packages/tui-adapter-react/src/components/prompt/prompt_renderer.tsx
import { TextAttributes } from '@opentui/core'

import { useTheme } from '../../hooks/index.ts'

import type {
  PromptData,
  ChoicePromptData,
  ConfirmPromptData,
  InputPromptData,
  MultiChoicePromptData,
  PromptTheme,
} from '@navios/commander-tui'

export interface PromptRendererProps {
  prompt: PromptData
}

export function PromptRenderer({ prompt }: PromptRendererProps) {
  const theme = useTheme()
  // Calculate timeout remaining if applicable
  const timeoutRemaining = getTimeoutRemaining(prompt)

  switch (prompt.type) {
    case 'choice':
      return (
        <ChoicePromptRenderer
          prompt={prompt}
          timeoutRemaining={timeoutRemaining}
          colors={theme.prompt}
        />
      )
    case 'confirm':
      return (
        <ConfirmPromptRenderer
          prompt={prompt}
          timeoutRemaining={timeoutRemaining}
          colors={theme.prompt}
        />
      )
    case 'input':
      return (
        <InputPromptRenderer
          prompt={prompt}
          timeoutRemaining={timeoutRemaining}
          colors={theme.prompt}
        />
      )
    case 'multiChoice':
      return (
        <MultiChoicePromptRenderer
          prompt={prompt}
          timeoutRemaining={timeoutRemaining}
          colors={theme.prompt}
        />
      )
    default:
      return null
  }
}

function getTimeoutRemaining(prompt: PromptData): number | null {
  if (!prompt.timeout || !prompt.timeoutStarted) return null
  const elapsed = Date.now() - prompt.timeoutStarted
  const remaining = Math.max(0, prompt.timeout - elapsed)
  return Math.ceil(remaining / 1000)
}

function TimeoutIndicator({ seconds, colors }: { seconds: number | null; colors: PromptTheme }) {
  if (seconds === null) return null
  return (
    <text fg={colors.optionTextDim} attributes={TextAttributes.DIM}>
      {' '}
      (auto-select in {seconds}s)
    </text>
  )
}

interface ChoicePromptRendererProps {
  prompt: ChoicePromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function ChoicePromptRenderer({ prompt, timeoutRemaining, colors }: ChoicePromptRendererProps) {
  return (
    <box
      flexDirection="column"
      borderColor={colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={colors.question} attributes={TextAttributes.BOLD}>
          ? {prompt.question}
        </text>
        <TimeoutIndicator seconds={timeoutRemaining} colors={colors} />
      </box>

      {/* Choices */}
      <box flexDirection="column">
        {prompt.choices.map((choice, index) => {
          const isSelected = index === prompt.selectedIndex
          const showInput = isSelected && choice.input && prompt.inputMode

          return (
            <box key={choice.value} flexDirection="row">
              {/* Selection indicator */}
              <text fg={isSelected ? colors.optionSelected : 'transparent'}>{'>'} </text>

              {/* Choice label */}
              <text
                fg={isSelected ? colors.optionText : colors.optionTextDim}
                attributes={isSelected ? TextAttributes.BOLD : undefined}
              >
                {choice.label}
              </text>

              {/* Input field (if applicable) */}
              {showInput && (
                <box flexDirection="row" marginLeft={1}>
                  <text fg={colors.inputText}>: </text>
                  <text fg={colors.inputText}>{prompt.inputValue}</text>
                  <text fg={colors.inputCursor} attributes={TextAttributes.BLINK}>
                    _
                  </text>
                </box>
              )}

              {/* Show hint for input option when selected but not in input mode */}
              {isSelected && choice.input && !prompt.inputMode && (
                <text fg={colors.optionTextDim}> (press Enter to type)</text>
              )}
            </box>
          )
        })}
      </box>

      {/* Instructions */}
      {prompt.inputMode ? (
        <text fg={colors.optionTextDim} attributes={TextAttributes.DIM}>
          Type your answer, Enter to submit, Esc to cancel
        </text>
      ) : (
        <text fg={colors.optionTextDim} attributes={TextAttributes.DIM}>
          ↑/↓ to navigate, Enter to select
        </text>
      )}
    </box>
  )
}

interface ConfirmPromptRendererProps {
  prompt: ConfirmPromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function ConfirmPromptRenderer({ prompt, timeoutRemaining, colors }: ConfirmPromptRendererProps) {
  const confirmSelected = prompt.selectedValue === true
  const cancelSelected = prompt.selectedValue === false

  return (
    <box
      flexDirection="column"
      borderColor={colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={colors.question} attributes={TextAttributes.BOLD}>
          ? {prompt.question}
        </text>
        <TimeoutIndicator seconds={timeoutRemaining} colors={colors} />
      </box>

      {/* Buttons */}
      <box flexDirection="row" gap={2}>
        {/* Confirm button */}
        <box
          backgroundColor={confirmSelected ? colors.buttonSelectedBackground : undefined}
          paddingLeft={1}
          paddingRight={1}
        >
          <text
            fg={confirmSelected ? colors.confirmButton : colors.optionTextDim}
            attributes={confirmSelected ? TextAttributes.BOLD : undefined}
          >
            {confirmSelected ? '>' : ' '} {prompt.confirmText}
          </text>
        </box>

        {/* Cancel button */}
        <box
          backgroundColor={cancelSelected ? colors.buttonSelectedBackground : undefined}
          paddingLeft={1}
          paddingRight={1}
        >
          <text
            fg={cancelSelected ? colors.cancelButton : colors.optionTextDim}
            attributes={cancelSelected ? TextAttributes.BOLD : undefined}
          >
            {cancelSelected ? '>' : ' '} {prompt.cancelText}
          </text>
        </box>
      </box>

      {/* Instructions */}
      <text fg={colors.optionTextDim} attributes={TextAttributes.DIM}>
        ←/→ to select, Enter to confirm
      </text>
    </box>
  )
}

interface InputPromptRendererProps {
  prompt: InputPromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function InputPromptRenderer({ prompt, timeoutRemaining, colors }: InputPromptRendererProps) {
  const hasValue = prompt.value.length > 0

  return (
    <box
      flexDirection="column"
      borderColor={colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={colors.question} attributes={TextAttributes.BOLD}>
          ? {prompt.question}
        </text>
        <TimeoutIndicator seconds={timeoutRemaining} colors={colors} />
      </box>

      {/* Input field */}
      <box flexDirection="row" borderColor={colors.inputBorder} border={['left']} paddingLeft={1}>
        <text fg={hasValue ? colors.inputText : colors.inputPlaceholder}>
          {hasValue ? prompt.value : prompt.placeholder}
        </text>
        <text fg={colors.inputCursor} attributes={TextAttributes.BLINK}>
          _
        </text>
      </box>

      {/* Instructions */}
      <text fg={colors.optionTextDim} attributes={TextAttributes.DIM}>
        Type your answer, Enter to submit
      </text>
    </box>
  )
}

interface MultiChoicePromptRendererProps {
  prompt: MultiChoicePromptData
  timeoutRemaining: number | null
  colors: PromptTheme
}

function MultiChoicePromptRenderer({
  prompt,
  timeoutRemaining,
  colors,
}: MultiChoicePromptRendererProps) {
  const selectedCount = prompt.selectedIndices.size
  const canSubmit = selectedCount >= prompt.minSelect

  return (
    <box
      flexDirection="column"
      borderColor={colors.focusBorder}
      border={['left']}
      paddingLeft={1}
      paddingRight={1}
      gap={1}
    >
      {/* Question */}
      <box flexDirection="row">
        <text fg={colors.question} attributes={TextAttributes.BOLD}>
          ? {prompt.question}
        </text>
        <text fg={colors.optionTextDim}>
          {' '}
          ({selectedCount}/{prompt.maxSelect} selected)
        </text>
        <TimeoutIndicator seconds={timeoutRemaining} colors={colors} />
      </box>

      {/* Choices */}
      <box flexDirection="column">
        {prompt.choices.map((choice, index) => {
          const isFocused = index === prompt.focusedIndex
          const isChecked = prompt.selectedIndices.has(index)

          return (
            <box key={choice.value} flexDirection="row">
              {/* Focus indicator */}
              <text fg={isFocused ? colors.optionSelected : 'transparent'}>{'>'} </text>

              {/* Checkbox */}
              <text fg={isChecked ? colors.optionSelected : colors.optionTextDim}>
                {isChecked ? '[✓]' : '[ ]'}{' '}
              </text>

              {/* Choice label */}
              <text
                fg={isFocused ? colors.optionText : colors.optionTextDim}
                attributes={isFocused ? TextAttributes.BOLD : undefined}
              >
                {choice.label}
              </text>
            </box>
          )
        })}
      </box>

      {/* Instructions */}
      <box flexDirection="column">
        <text fg={colors.optionTextDim} attributes={TextAttributes.DIM}>
          ↑/↓ to navigate, Space to toggle
        </text>
        {canSubmit ? (
          <text fg={colors.optionTextDim} attributes={TextAttributes.DIM}>
            Enter to confirm
          </text>
        ) : (
          <text fg={colors.cancelButton} attributes={TextAttributes.DIM}>
            Select at least {prompt.minSelect} option
            {prompt.minSelect > 1 ? 's' : ''}
          </text>
        )}
      </box>
    </box>
  )
}
