// packages/tui-adapter-solid/src/hooks/use_manager_store.ts
import { createSignal, createEffect, onCleanup } from 'solid-js'

import type { ScreenManagerInstance, ScreenInstance, FocusArea } from '@navios/commander-tui'
import type { Accessor } from 'solid-js'

/**
 * Creates a reactive accessor for the active screen.
 * Subscribes to the `activeScreen:changed` event.
 */
export function createActiveScreen(
  manager: ScreenManagerInstance,
): Accessor<ScreenInstance | null> {
  const [activeScreen, setActiveScreen] = createSignal<ScreenInstance | null>(
    manager.getActiveScreen(),
  )

  createEffect(() => {
    const handler = () => {
      setActiveScreen(manager.getActiveScreen())
    }

    manager.on('activeScreen:changed', handler)

    onCleanup(() => {
      manager.off('activeScreen:changed', handler)
    })
  })

  return activeScreen
}

/**
 * Creates a reactive accessor for the focus area (sidebar vs content).
 * Subscribes to the `focus:changed` event.
 */
export function createFocusArea(manager: ScreenManagerInstance): Accessor<FocusArea> {
  const [focusArea, setFocusArea] = createSignal<FocusArea>(manager.focusArea)

  createEffect(() => {
    const handler = () => {
      setFocusArea(manager.focusArea)
    }

    manager.on('focus:changed', handler)

    onCleanup(() => {
      manager.off('focus:changed', handler)
    })
  })

  return focusArea
}

/**
 * Creates a reactive accessor for the screen list.
 * Subscribes to screen lifecycle events (add/remove/reorder/visibility).
 */
export function createScreenList(manager: ScreenManagerInstance): Accessor<ScreenInstance[]> {
  const [screens, setScreens] = createSignal<ScreenInstance[]>(manager.getScreens())

  createEffect(() => {
    const events = [
      'screen:added',
      'screen:removed',
      'screen:reordered',
      'visibility:changed',
    ] as const

    const handler = () => {
      setScreens(manager.getScreens())
    }

    for (const event of events) {
      manager.on(event as 'screen:added', handler)
    }

    onCleanup(() => {
      for (const event of events) {
        manager.off(event as 'screen:added', handler)
      }
    })
  })

  return screens
}

/**
 * Creates a reactive accessor for the sidebar index.
 * Subscribes to the `sidebar:indexChanged` event.
 */
export function createSidebarIndex(manager: ScreenManagerInstance): Accessor<number> {
  const [sidebarIndex, setSidebarIndex] = createSignal<number>(manager.selectedIndex)

  createEffect(() => {
    const handler = () => {
      setSidebarIndex(manager.selectedIndex)
    }

    manager.on('sidebar:indexChanged', handler)

    onCleanup(() => {
      manager.off('sidebar:indexChanged', handler)
    })
  })

  return sidebarIndex
}

// packages/tui-adapter-react/src/hooks/use_manager_store.ts
import { useCallback, useSyncExternalStore } from 'react'

import type { ScreenManagerInstance, ScreenInstance, FocusArea } from '@navios/commander-tui'

const EMPTY_SCREENS: ScreenInstance[] = []

// External cache for screen lists, keyed by manager instance
// This ensures getSnapshot returns stable references as required by useSyncExternalStore
const screenListCache = new WeakMap<ScreenManagerInstance, ScreenInstance[]>()

/**
 * Hook to subscribe to the active screen changes.
 */
export function useActiveScreen(manager: ScreenManagerInstance): ScreenInstance | null {
  return useSyncExternalStore(
    (onStoreChange) => {
      manager.on('activeScreen:changed', onStoreChange)
      return () => manager.off('activeScreen:changed', onStoreChange)
    },
    () => manager.getActiveScreen(),
    () => manager.getActiveScreen(),
  )
}

/**
 * Hook to subscribe to focus area changes (sidebar vs content).
 */
export function useFocusArea(manager: ScreenManagerInstance): FocusArea {
  return useSyncExternalStore(
    (onStoreChange) => {
      manager.on('focus:changed', onStoreChange)
      return () => manager.off('focus:changed', onStoreChange)
    },
    () => manager.focusArea,
    () => manager.focusArea,
  )
}

/**
 * Hook to subscribe to the screen list (add/remove/reorder).
 * Uses external cache to ensure getSnapshot returns stable references.
 */
export function useScreenList(manager: ScreenManagerInstance): ScreenInstance[] {
  const subscribe = useCallback(
    (onStoreChange: () => void) => {
      const events = [
        'screen:added',
        'screen:removed',
        'screen:reordered',
        'visibility:changed',
      ] as const

      const handleChange = () => {
        // Update cache when data changes
        screenListCache.set(manager, manager.getScreens())
        onStoreChange()
      }

      for (const event of events) {
        manager.on(event as 'screen:added', handleChange)
      }
      return () => {
        for (const event of events) {
          manager.off(event as 'screen:added', handleChange)
        }
      }
    },
    [manager],
  )

  const getSnapshot = useCallback(() => {
    // Return cached value if available, otherwise initialize cache
    let cached = screenListCache.get(manager)
    if (!cached) {
      cached = manager.getScreens()
      screenListCache.set(manager, cached)
    }
    return cached
  }, [manager])

  return useSyncExternalStore(subscribe, getSnapshot, () => EMPTY_SCREENS)
}

/**
 * Hook to subscribe to sidebar index changes.
 */
export function useSidebarIndex(manager: ScreenManagerInstance): number {
  return useSyncExternalStore(
    (onStoreChange) => {
      manager.on('sidebar:indexChanged', onStoreChange)
      return () => manager.off('sidebar:indexChanged', onStoreChange)
    },
    () => manager.selectedIndex,
    () => 0,
  )
}
